// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BestPracticesCodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "BestPracticesCodeGenerator.1bda164c-2fba-43e6-91bb-424ac2a31dac";
        public const string Name = "Best Practices generator";
        public const string Description = @"Generate clean architecture structure with Best.Practices framework";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Elias Silva";
        public const string Tags = "C#, CSharp,Clean architecture, DDD, OOP, Repository, Unit Tests, Dapper, Productivity";
    }
}
