// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BestPracticesCodeGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BestPracticesCodeGeneratorString = "3a9553da-51e5-4df4-bb92-f7da402cc6ed";
        public static Guid BestPracticesCodeGenerator = new Guid(BestPracticesCodeGeneratorString);

        public const string guidBestPracticesCodeGeneratorPackageCmdSetString = "da2ba8c3-d21a-41e6-b2dd-fe079d5cbaf8";
        public static Guid guidBestPracticesCodeGeneratorPackageCmdSet = new Guid(guidBestPracticesCodeGeneratorPackageCmdSetString);

        public const string guidImagesString = "3bc7f790-9200-40f6-9d42-6f96023499af";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int SolutonItemContextMenuCommand = 0x0100;
        public const int EditorContextMenuGroup = 0x0101;
        public const int FileEditorContextMenuCommand = 0x0102;
        public const int cmdidfrmCodeGenerationOptionsCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}